[[LibCWebSocketsClient]]
arch = "aarch64"
git-tree-sha1 = "b65ea985638ab0f9e2992e6660466ab0627c3ca0"
os = "macos"

    [[LibCWebSocketsClient.download]]
    sha256 = "baa27424d6cf41d02676a634a31b59101f1745758d05cb3e341159de032081b8"
    url = "https://github.com/GlebZolotov/LibCWebSocketsClient_jll.jl/releases/download/LibCWebSocketsClient-v1.0.6+0/LibCWebSocketsClient.v1.0.6.aarch64-apple-darwin.tar.gz"
[[LibCWebSocketsClient]]
arch = "x86_64"
git-tree-sha1 = "6bb435a4df50fb5d6669ef546ff709a27e872922"
os = "macos"

    [[LibCWebSocketsClient.download]]
    sha256 = "d38acee011418b847db87ee4c4e0c86d7e0996ac77b7ed92edc7880fc20f300d"
    url = "https://github.com/GlebZolotov/LibCWebSocketsClient_jll.jl/releases/download/LibCWebSocketsClient-v1.0.6+0/LibCWebSocketsClient.v1.0.6.x86_64-apple-darwin.tar.gz"
[[LibCWebSocketsClient]]
arch = "x86_64"
git-tree-sha1 = "ae2126f06f84ac0b9ab77d0291ca6271745ce2fd"
libc = "glibc"
os = "linux"

    [[LibCWebSocketsClient.download]]
    sha256 = "18756520fc6f203b0b74d88be5b5e332ea622f40f8c8e6c240954bb0f55eefb3"
    url = "https://github.com/GlebZolotov/LibCWebSocketsClient_jll.jl/releases/download/LibCWebSocketsClient-v1.0.6+0/LibCWebSocketsClient.v1.0.6.x86_64-linux-gnu.tar.gz"
