# Autogenerated wrapper script for LibCWebSocketsClient_jll for x86_64-linux-gnu
export c_libwebsockets, lib_c_websockets_client

using Zlib_jll
using OpenSSL_jll
JLLWrappers.@generate_wrapper_header("LibCWebSocketsClient")
JLLWrappers.@declare_library_product(c_libwebsockets, "libwebsockets.so.19")
JLLWrappers.@declare_library_product(lib_c_websockets_client, "websockets_client.so")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, OpenSSL_jll)
    JLLWrappers.@init_library_product(
        c_libwebsockets,
        "lib/libwebsockets.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        lib_c_websockets_client,
        "lib/websockets_client.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
